services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./volumes/qdrant:/qdrant/storage
  ollama-server:
    build:
      context: src/main/docker/ollama
    volumes:
      - ./volumes/ollama:/root/.ollama
    ports:
      - "11434:11434"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:11434 || exit 1" ]
      start_period: 3s
      interval: 3s
  ollama-model:
    image: ollama/ollama:latest
    command:
      - run
      - llama3.2:1b
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
    depends_on:
      ollama-server:
        condition: service_healthy
  ollama-embeddings:
    image: ollama/ollama:latest
    command:
      - run
      - nomic-embed-text
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
    depends_on:
      ollama-server:
        condition: service_healthy
