name: Continuous Integration - Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up JDK 21"
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"
          cache: maven

      - name: "Build with Maven"
        run: mvn --batch-mode --update-snapshots verify

      - name: "Create GitHub Release"
        if: ${{ startsWith(github.ref, 'refs/tags/') && startsWith(github.event.head_commit.message, 'chore(release)') }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/togaf-expairt.jar"
          omitName: true
          omitBody: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
