name: Continuous Integration - Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Set up JDK 21"
        uses: actions/setup-java@v2
        with:
          java-version: "21"
          distribution: "adopt"
          cache: maven

      - name: Cache Docker Volumes
        id: volumes
        uses: actions/cache@v4
        with:
          path: volumes
          key: ${{ runner.os }}-volumes

      - name: Cache Maven Dependencies
        id: maven
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: "Build with Maven"
        run: ./mvnw verify

      - name: "Chown Docker Volumes"
        run: sudo chown -R $USER:$USER volumes

      - name: "Create GitHub Release"
        if: ${{ startsWith(github.ref, 'refs/tags/') && startsWith(github.event.head_commit.message, 'chore(release)') }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "target/togaf-expairt.jar"
          omitName: true
          omitBody: true
          draft: false
          token: ${{ secrets.GITHUB_TOKEN }}
